# Generated by Django 2.2.1 on 2019-05-14 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sede', models.CharField(max_length=255, verbose_name='Nombre Sede')),
                ('direccion', models.CharField(max_length=255, verbose_name='Direccion Sede')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['nombre_sede'],
            },
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prueba', models.CharField(max_length=255, verbose_name='Tipo de test')),
                ('fecha_prueba', models.DateField(verbose_name='Fecha de la prueba')),
                ('hora_inicio', models.DateTimeField(verbose_name='Hora de inicio')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pruebas', to='core.Sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Prueba',
                'verbose_name_plural': 'Pruebas',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('carrera', models.CharField(max_length=255, verbose_name='Carrera')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Alumnos', to='core.Prueba', verbose_name='Prueba')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['created'],
            },
        ),
    ]
