# Generated by Django 2.2.1 on 2019-05-14 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='hora_fin',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 23, 11, 26, 427898), verbose_name='Hora de fin'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='hora_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 23, 11, 26, 427870), verbose_name='Hora de inicio'),
        ),
    ]
