# Generated by Django 2.2.1 on 2019-05-14 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190514_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='hora_fin',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 23, 14, 6, 766992), verbose_name='Hora de fin'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='hora_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 23, 14, 6, 766959), verbose_name='Hora de inicio'),
        ),
    ]
