# Generated by Django 2.2.1 on 2019-05-15 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190514_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='hora_fin',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 9, 42, 6, 593623), verbose_name='Hora de fin'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='hora_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 9, 42, 6, 593587), verbose_name='Hora de inicio'),
        ),
    ]
