# Generated by Django 2.2.1 on 2019-05-15 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190515_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='hora_fin',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 9, 48, 15, 546154), verbose_name='Hora de fin'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='hora_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 9, 48, 15, 546127), verbose_name='Hora de inicio'),
        ),
    ]
