# Generated by Django 2.2.1 on 2019-05-15 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190515_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='hora_fin',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 9, 51, 51, 429897), verbose_name='Hora de fin'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='hora_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 9, 51, 51, 429863), verbose_name='Hora de inicio'),
        ),
    ]
