# Generated by Django 2.2.1 on 2019-05-15 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190515_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='hora_fin',
            field=models.CharField(max_length=255, verbose_name='Hora Fin'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='hora_inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 9, 52, 27, 620910), verbose_name='Hora de inicio'),
        ),
    ]
