# Generated by Django 2.2.1 on 2019-05-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190515_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='hora_inicio',
            field=models.DateTimeField(max_length=255, verbose_name='Hora inicio'),
        ),
    ]
