# Generated by Django 2.2.1 on 2019-05-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190515_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='docente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Docente'),
        ),
        migrations.AddField(
            model_name='prueba',
            name='sala',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='tipo_prueba',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de test'),
        ),
    ]
